# postgresql \u0438\u043b\u0438 mysql
db.type=postgresql

# PostgreSQL
db.url=jdbc:postgresql://localhost:5432/car_service_db
db.user=postgres
db.password=postgres

# MySQL db.type=mysql
# db.url=jdbc:mysql://localhost:3306/car_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# db.user=root
# db.password=mishaMISHA
